name: web-sitecopy
  
on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *' 
  
jobs:  
  build:  
    runs-on: windows-latest  
  
    steps:  
    - uses: actions/checkout@v2  
  
    # 安装Python  
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12" 
  
    # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: cmd
      run: wget.bat
   
      # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://19870310.xyz/
  
       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://qbxd.19870310.xyz/sitecopy
   
       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://gmxx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://jczx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://kcxx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://mh3z.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://mh4z.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://mjyfz.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://mqsx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://pj1z.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://qbxd.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://qzxx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://sszx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://stx.19870310.xyz/sitecopy

       # 运行sitecopy脚本  
    - name: Run sitecopy-web.bat
      shell: bash
      run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -e robots=off -P / https://zdxx.19870310.xyz/sitecopy